### ISSUE TITLE
inline-функции, linkage и ODR-use

### ISSUE THREAD

**Issue by andtit2001** [yuri-pechatnov/caos_2019-2020#1]
https://github.com/yuri-pechatnov/caos_2019-2020/blob/820ce4fd0a40d29e1c6e307ef2dc7ec5cd3ebfd9/sem22-dynamic-lib/README.md#L485-L487
Я считаю, что комментарий к функции `SumB` может ввести читателя в заблуждение, поскольку стандарт языка C++ не гарантирует, что `SumB` будет отсутствовать в таблице символов.

1. Почему не гарантируется отсутствие? Потому что `SumB` имеет external linkage, несмотря на (неявное) наличие спецификатора `inline`.
2. Почему в данном случае `SumB` всё же отсутствует в таблице символов? Есть предположение, что GCC удаляет inline-функции, которые не являются ODR-used.

В связи с этим предлагаю переписать комментарии к функциям `SumB` и `SumC`.

**Comment by yuri-pechatnov** [comment]
https://github.com/yuri-pechatnov/caos_2019-2020/tree/master/sem22-dynamic-lib#odr_inline
Так нормально?

**Comment by andtit2001** [comment]
Да, вполне нормально.

Немного вкусовщины: я бы явно указал, что `inline` &mdash; это спецификатор [[cppref]](https://en.cppreference.com/w/cpp/language/inline)[[std.dcl.inline]](http://eel.is/c++draft/dcl.inline), используемый для объявления _inline function_ [[cppref]](https://en.cppreference.com/w/cpp/language/inline#Description)[[std.dcl.inline]](http://eel.is/c++draft/dcl.inline#2), и функции, определённые в теле класса, являются inline [[std.class.mcft]](http://eel.is/c++draft/class.mfct#1)[[std.class.friend]](http://eel.is/c++draft/class.friend#6).

**Comment by yuri-pechatnov** [comment]
Последнее добавил
